[redis.default]
	addr = "192.168.0.230:6380"
	user = "root"
	pawd = ""
	dial_timeout = 5000
	read_timeout = 5000
	write_timeout = 5000
	pool_max_idle = 5
	pool_max_active = 10
	pool_wait = true
	pool_idle_time = 60000
	pool_max_conn_life_time = 60000
